import "./globals.css";

import { Analytics } from "@vercel/analytics/react";
import { Header } from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
      ></meta>
      <body
        className="min-h-screen flex flex-col items-center w-full bg-white"
        suppressHydrationWarning={true}
      >
        <Header />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
